<?php

namespace AppBundle\Repository;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Entity\technologie;
use AppBundle\Entity\cv;
use AppBundle\Entity\candidat;
use \Datetime;
use AppBundle\Entity\diplome;
use AppBundle\Entity\ecole;
use AppBundle\Entity\certification;
use AppBundle\Entity\entreprise;

/**
 * candidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class candidatRepository extends \Doctrine\ORM\EntityRepository
{
    
    protected function persistAndFlush($entity)
    {
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();
        
    }
    
    protected function removeAndFlush($entity)
    {
        $this->getEntityManager()->remove($entity);
        $this->getEntityManager()->flush();
        
    }
    
    public function findAll()
    {
        return $this->findBy(array('etat' => 'Active'), array('prenom' => 'ASC'));
    }
    
    public function showAllCandidats()
    {
        $candidats = $this->findAll();
        
        $listeFinaleCandidats = array();
 
        foreach ($candidats as $candidat)
        {
            $photo = "bootstrap/img/profile.jpg";
            
            if(!empty($candidat->getPhoto()))
            {
                $photo = $candidat->getPhoto();
            }
            
            $anneeDemarrageCarriere = "N/A";
            
            if(!empty($candidat->getAnneeDemarrageCarriere()))
            {
                $anneeDemarrageCarriere = $candidat->getAnneeDemarrageCarriere();
            }
            
            $entreprise = "";
            
            if(!empty($candidat->getEntreprise()))
            {
                $entreprise = $candidat->getEntreprise()->getNom();
                $idEntreprise = $candidat->getEntreprise()->getId();
                $siteWebEntreprise = $candidat->getEntreprise()->getSiteWeb();
            }
            
            $listeCandidats = Array(
                'id' => $candidat->getId(),
                'prenom' => $candidat->getPrenom(),
                'nom' => $candidat->getNom(),
                'specialite' => $candidat->getSpecialite(),
                'telephone' => $candidat->getTelephone(),
                'anneeDemarrageCarriere' => $anneeDemarrageCarriere,
                'photo' => $photo,
                'visa' => $candidat->getVisa(),
                'etat' => $candidat->getEtat(),
                'entreprise' => $entreprise,
                'idEntreprise' => $idEntreprise,
                'siteWebEntreprise' => $siteWebEntreprise,
                'listeTechnologies' => $candidat->getListeTechnologies()
                );
            
            $listeFinaleCandidats[] = $listeCandidats;
        }
        return $listeFinaleCandidats;
        
    }
    
    public function showAllCandidatsLight()
    {
        $candidats = $this->findAll();
        
        $listeFinaleCandidats = array();
        
        foreach ($candidats as $candidat)
        {
            $photo = "bootstrap/img/profile.jpg";
            
            if(!empty($candidat->getPhoto()))
            {
                $photo = $candidat->getPhoto();
            }
            
            $listeCandidats = Array(
                'id' => $candidat->getId(),
                'prenom' => $candidat->getPrenom(),
                'nom' => $candidat->getNom(),
                'specialite' => $candidat->getSpecialite(),
                'etat' => $candidat->getEtat(),
                'photo' => $photo
                
                );
            
            $listeFinaleCandidats[] = $listeCandidats;
        }
        return $listeFinaleCandidats;
        
    }
    
    public function showOneCandidat($idCandidat) 
    {
        
        $candidat = $this->findOneBy(array('id' => $idCandidat));
        
        $dateDeNaissance = "N/A";
        $dateDeDisponibilite = "N/A";
        $photo = "bootstrap/img/profile.jpg";
        $situationFamiliale = "N/A";
        $adresse = "N/A";
        $telephone = "N/A";
        $email = "N/A";
        $idDiplomeCandidat="";
        $nomDiplomeCandidat="";
        $idEcoleCandidat="";
        $nomEcoleCandidat="";
        $entreprise = "";
        $idEntreprise = "";
        $siteWebEntreprise="";
        
        if(!empty($candidat->getDateDeNaissance()))
        {
            $dateDeNaissance = $candidat->getDateDeNaissance()->format('d-m-Y');
        }
        
        if(!empty($candidat->getDateDeDisponibilite()))
        {
            $dateDeDisponibilite = $candidat->getDateDeDisponibilite()->format('d-m-Y');
        }
        
        if(!empty($candidat->getPhoto()))
        {
            $photo = $candidat->getPhoto();
        }
        
        if(!empty($candidat->getSituationFamiliale()))
        {
            $situationFamiliale = $candidat->getSituationFamiliale();
        }
        
        if(!empty($candidat->getAdresse()))
        {
            $adresse = $candidat->getAdresse();
        }
        
        if(!empty($candidat->getTelephone()))
        {
            $telephone = $candidat->getTelephone();
        }
        
        if(!empty($candidat->getEmail()))
        {
            $email = $candidat->getEmail();
        }
        
        //Affichage du diplome : utile uniquement pour la Modification
        foreach ($candidat->getListeDiplomes() as $diplome) {
            $idDiplomeCandidat = $diplome->getId();
            $nomDiplomeCandidat = $diplome->getNom();
        }
        
        //Affichage de l'école : utile uniquement pour la Modification
        foreach ($candidat->getListeEcoles() as $ecole) {
            $idEcoleCandidat = $ecole->getId();
            $nomEcoleCandidat = $ecole->getNom();
        }
        
        if(!empty($candidat->getEntreprise()))
        {
            $entreprise = $candidat->getEntreprise()->getNom();
            $idEntreprise = $candidat->getEntreprise()->getId();
            $siteWebEntreprise = $candidat->getEntreprise()->getSiteWeb();
        }
       
        
        $detailsCandidat = Array(
            'id' => $candidat->getId(),
            'prenom' => $candidat->getPrenom(),
            'nom' => $candidat->getNom(),    
            'dateDeNaissance' => $dateDeNaissance,
            'adresse' => $adresse,
            'telephone' => $telephone,
            'email' => $email,
            'specialite' => $candidat->getSpecialite(),
            'anneeGraduation' => $candidat->getAnneeGraduation(),
            'anneeDemarrageCarriere' => $candidat->getAnneeDemarrageCarriere(),
            'situationFamiliale' => $situationFamiliale,
            'nombreEnfants' => $candidat->getNombreEnfants(),
            'photo' => $photo,
            'salaireActuel' => $candidat->getSalaireActuel(),
            'pretentionSalariale' => $candidat->getPretentionSalariale(),
            'niveauEnFrancais' => $candidat->getNiveauEnFrancais(),
            'niveauEnAnglais' => $candidat->getNiveauEnAnglais(),
            'noteGlobale' => $candidat->getNoteGlobale(),
            'descriptionDetaillee' => $candidat->getDescriptionDetaillee(),
            'preavis' => $candidat->getPreavis(),
            'dateDeDisponibilite' => $dateDeDisponibilite,
            'visa' => $candidat->getVisa(),
            'etat' => $candidat->getEtat(),
            'entreprise' => $entreprise,
            'idEntreprise' => $idEntreprise,
            'siteWebEntreprise' => $siteWebEntreprise,
            
            'idDiplomeCandidat' => $idDiplomeCandidat,
            'nomDiplomeCandidat' => $nomDiplomeCandidat,
            
            'idEcoleCandidat' => $idEcoleCandidat,
            'nomEcoleCandidat' => $nomEcoleCandidat,
            
            
            //Listes : ArrayCollections
            'listeCvs' => $candidat->getListeCvs(),
            'listeTechnologies' => $candidat->getListeTechnologies(),
            'listeCertifications' => $candidat->getListeCertifications(),
            'listeDiplomes' => $candidat->getListeDiplomes(),
            'listeEcoles' => $candidat->getListeEcoles()
                
                );
        
        
        return $detailsCandidat;
    }

    public function addCandidat($request)
    {
        
        $candidat = new candidat();
        
        $candidat->setEtat("Active");
        
        if(!empty($request->get('prenom')))
        {
            $candidat->setPrenom($request->get('prenom'));
        }
        
        if(!empty($request->get('nom')))
        {
            $candidat->setNom($request->get('nom'));
        }
        
        if(!empty($request->get('dateDeNaissance')))
        {
            $candidat->setDateDeNaissance(new DateTime($request->get('dateDeNaissance')));
        }else{
            $candidat->setDateDeNaissance(new DateTime('01-01-1970'));
        }
        
        if(!empty($request->get('telephone')))
        {
            $candidat->setTelephone($request->get('telephone'));
        }
        
        if(!empty($request->get('email')))
        {
            $candidat->setEmail($request->get('email'));
        }
        
        if(!empty($request->get('specialite')))
        {
            $candidat->setSpecialite($request->get('specialite'));
        }
        
        if(!empty($request->get('anneeGraduation')))
        {
            $candidat->setAnneeGraduation($request->get('anneeGraduation'));
        }
        
        if(!empty($request->get('anneeDemarrageCarriere')))
        {
            $candidat->setAnneeDemarrageCarriere($request->get('anneeDemarrageCarriere'));
        }
        
        if(!empty($request->get('situationFamiliale')))
        {
            $candidat->setSituationFamiliale($request->get('situationFamiliale'));
        }
        
        if($request->get('nombreEnfants')!=null)
        {
            $candidat->setNombreEnfants($request->get('nombreEnfants'));
        }

        //Ajout de la Photo
        if(!empty($_FILES["photoTelechargement"]["name"]))
        {
            $candidat->setPhoto($this->uploadFile("photoTelechargement"));
        }
        
        if(!empty($request->get('salaireActuel')))
        {
            $candidat->setSalaireActuel($request->get('salaireActuel'));
        }
        
        if(!empty($request->get('pretentionSalariale')))
        {
            $candidat->setPretentionSalariale($request->get('pretentionSalariale'));
        }
        
        if(!empty($request->get('niveauEnFrancais')))
        {
            $candidat->setNiveauEnFrancais($request->get('niveauEnFrancais'));
        }
        
        if(!empty($request->get('niveauEnAnglais')))
        {
            $candidat->setNiveauEnAnglais($request->get('niveauEnAnglais'));
        }
        
        if(!empty($request->get('noteGlobale')))
        {
            $candidat->setNoteGlobale($request->get('noteGlobale'));
        }
        
        if(!empty($request->get('descriptionDetaillee')))
        {
            $candidat->setDescriptionDetaillee($request->get('descriptionDetaillee'));
        }
        
        if(!empty($request->get('preavis')))
        {
            $candidat->setPreavis($request->get('preavis'));
        }
        
        if(!empty($request->get('dateDeDisponibilite')))
        {
            $candidat->setDateDeDisponibilite(new DateTime($request->get('dateDeDisponibilite')));
        }else{
            $candidat->setDateDeDisponibilite(new DateTime('01-01-1970'));
        }
        
        if(!empty($request->get('adresse')))
        {
            $candidat->setAdresse($request->get('adresse'));
        }
        
        if(!empty($request->get('visa')))
        {
            $candidat->setVisa($request->get('visa'));
        }
        
        //Ajout de l'Entreprise
        if(!empty($request->get('listeEntreprises')))
        {
            $entrepriseRepository = $this->getEntityManager()->getRepository(entreprise::class);
            $entreprise = $entrepriseRepository->findOneBy(array('id' => $request->get('listeEntreprises')));
            $candidat->setEntreprise($entreprise);
        }
        
        
        //Ajout de Diplôme
        if(!empty($request->get('listeDiplomes')))
        {
            $diplomeRepository = $this->getEntityManager()->getRepository(diplome::class);
            $diplome = $diplomeRepository->findOneBy(array('id' => $request->get('listeDiplomes')));
            $candidat->addDiplome($diplome);
        }
        
        //Ajout de l'École
        if(!empty($request->get('listeEcoles')))
        {
            $ecoleRepository = $this->getEntityManager()->getRepository(ecole::class);
            $ecole = $ecoleRepository->findOneBy(array('id' => $request->get('listeEcoles')));
            $candidat->addEcole($ecole); 
        }
        
        //Ajout des technologies (une ou plusieurs)
        if(!empty($_POST['listeTechnologies']))
        {
            //Parcours et Ajout des technologies
            foreach ($_POST['listeTechnologies'] as $Technologie)
            {
                $technologieRepository = $this->getEntityManager()->getRepository(technologie::class);
                $technologie = $technologieRepository->findOneBy(array('id' => $Technologie));
                
                if(empty($technologie))
                {
                    $technologie = new technologie();
                    $technologie->setNom($technologie);
                    $this->persistAndFlush($technologie);
                }
                $candidat->addTechnologie($technologie);
            }  
            $this->persistAndFlush($candidat);
        }
        
        //Ajout des certifications (une ou plusieurs)
        if(!empty($_POST['listeCertifications']))
        {
            //Parcours et Ajout des certifications
            foreach ($_POST['listeCertifications'] as $Certification)
            {
                $certificationRepository = $this->getEntityManager()->getRepository(certification::class);
                $certification = $certificationRepository->findOneBy(array('id' => $Certification));
                
                if(empty($certification))
                {
                    $certification = new certification();
                    $certification->setNom($Certification);
                    $this->persistAndFlush($certification);
                }
                $candidat->addCertification($certification);
            }
            $this->persistAndFlush($candidat);
        }
        
        //Ajout de CV Original
        if(!empty($_FILES["cvOriginal"]["name"]))
        {
            $cvOriginal = new cv();
            $cvOriginal->setNom("CV Original");
            $fileName = $this->uploadFile("cvOriginal");
            $cvOriginal->setUrl($fileName);
            $candidat->addCv($cvOriginal);
            $this->persistAndFlush($cvOriginal);
        }
        
        //Ajout de CV Odix
        if(!empty($_FILES["cvOdix"]["name"]))
        {
            $cvOdix = new cv();
            $cvOdix->setNom("CV Odix");
            $fileName = $this->uploadFile("cvOdix");
            $cvOdix->setUrl($fileName);
            $candidat->addCv($cvOdix);
            $this->persistAndFlush($cvOdix);
         }
        
        $this->persistAndFlush($candidat);
    }
    
    public function updateCandidat($request)
    {
        
        $candidat = $this->findOneBy(array('id' => $request->get('id')));
        
        if(!empty($request->get('prenom')))
        {
            $candidat->setPrenom($request->get('prenom'));
        }
        
        if(!empty($request->get('nom')))
        {
            $candidat->setNom($request->get('nom'));
        }
        
        if(!empty($request->get('dateDeNaissance')))
        {
            $candidat->setDateDeNaissance(new DateTime($request->get('dateDeNaissance')));
        }
        
        if(!empty($request->get('telephone')))
        {
            $candidat->setTelephone($request->get('telephone'));
        }
        
        if(!empty($request->get('email')))
        {
            $candidat->setEmail($request->get('email'));
        }
        
        if(!empty($request->get('specialite')))
        {
            $candidat->setSpecialite($request->get('specialite'));
        }
        
        if(!empty($request->get('anneeGraduation')))
        {
            $candidat->setAnneeGraduation($request->get('anneeGraduation'));
        }
        
        if(!empty($request->get('anneeDemarrageCarriere')))
        {
            $candidat->setAnneeDemarrageCarriere($request->get('anneeDemarrageCarriere'));
        }
        
        if(!empty($request->get('situationFamiliale')))
        {
            $candidat->setSituationFamiliale($request->get('situationFamiliale'));
        }
        
        if($request->get('nombreEnfants')!=null)
        {
            $candidat->setNombreEnfants($request->get('nombreEnfants'));
        }

        if($request->get('salaireActuel')!=null)//if(!empty($request->get('salaireActuel')))
        {
            $candidat->setSalaireActuel($request->get('salaireActuel'));
        }
        
        if($request->get('pretentionSalariale')!=null)//if(!empty($request->get('pretentionSalariale')))
        {
            $candidat->setPretentionSalariale($request->get('pretentionSalariale'));
        }
        
        if(!empty($request->get('niveauEnFrancais')))
        {
            $candidat->setNiveauEnFrancais($request->get('niveauEnFrancais'));
        }
        
        if(!empty($request->get('niveauEnAnglais')))
        {
            $candidat->setNiveauEnAnglais($request->get('niveauEnAnglais'));
        }
        
        if(!empty($request->get('noteGlobale')))
        {
            $candidat->setNoteGlobale($request->get('noteGlobale'));
        }
        
        if(!empty($request->get('descriptionDetaillee')))
        {
            $candidat->setDescriptionDetaillee($request->get('descriptionDetaillee'));
        }
        
        if(!empty($request->get('preavis')))
        {
            $candidat->setPreavis($request->get('preavis'));
        }

        if(!empty($request->get('dateDeDisponibilite')))
        {
            $candidat->setDateDeDisponibilite(new DateTime($request->get('dateDeDisponibilite')));
        }
        
        if(!empty($request->get('adresse')))
        {
            $candidat->setAdresse($request->get('adresse'));
        }
        
        if(!empty($request->get('visa')))
        {
            $candidat->setVisa($request->get('visa'));
        }
        
            //Ajout de l'Entreprise
        if(!empty($request->get('listeEntreprises')))
        {
            $entrepriseRepository = $this->getEntityManager()->getRepository(entreprise::class);
            $entreprise = $entrepriseRepository->findOneBy(array('id' => $request->get('listeEntreprises')));
            $candidat->setEntreprise($entreprise);
        }
        
        //Ajout de la Photo
        if(!empty($_FILES["photoTelechargement"]["name"]))
        {
            
            unlink($candidat->getPhoto());
            
            $candidat->setPhoto($this->uploadFile("photoTelechargement"));
        }
        
        //Ajout de Diplôme
        if(!empty($request->get('listeDiplomes')))
        {  
            $diplomeRepository = $this->getEntityManager()->getRepository(diplome::class);
            $diplome = $diplomeRepository->findOneBy(array('id' => $request->get('listeDiplomes')));
            
            //Si le diplôme n'existe pas dans la jointure alors on l'ajoute au candidat, ce test évite d'ajouter une ligne unique dans la jointure
            if (!$candidat->getListeDiplomes()->contains($diplome)) 
            {
                $candidat->addDiplome($diplome);
            } 
        }
       
        //Ajout de l'École
        if(!empty($request->get('listeEcoles')))
        {
            $ecoleRepository = $this->getEntityManager()->getRepository(ecole::class);
            $ecole = $ecoleRepository->findOneBy(array('id' => $request->get('listeEcoles')));
            
            //Si l'école n'existe pas dans la jointure alors on l'ajoute au candidat, ce test évite d'ajouter une ligne unique dans la jointure
            if (!$candidat->getListeEcoles()->contains($ecole)) 
            {
                $candidat->addEcole($ecole);
            }
        }
        
        //Update de CV Original
        if(!empty($_FILES["cvOriginal"]["name"]))
        {
            $listeCV = $candidat->getListeCvs();
            
            //Supprimer le old CV
            foreach ($listeCV as $cv)
            {
                if(strpos($cv->getNom(), 'Original') !== false)
                {
                    unlink($cv->getUrl());
                    $candidat->removeCv($cv);
                    $this->removeAndFlush($cv);
                }
            }
            
            //Ajouter le new CV
            $cvOriginal = new cv();
            $cvOriginal->setNom("CV Original");
            $fileName = $this->uploadFile("cvOriginal");
            $cvOriginal->setUrl($fileName);
            $candidat->addCv($cvOriginal);
            $this->persistAndFlush($cvOriginal);
        }
        
        
        //Update de CV Odix
        if(!empty($_FILES["cvOdix"]["name"]))
        {
            $listeCV = $candidat->getListeCvs();
            
            //Supprimer le old CV
            foreach ($listeCV as $cv)
            {
                if(strpos($cv->getNom(), 'Odix') !== false)
                {
                    unlink($cv->getUrl());
                    $candidat->removeCv($cv);
                    $this->removeAndFlush($cv);
                }
            }
            
            //Ajouter le new CV
            $cvOdix = new cv();
            $cvOdix->setNom("CV Odix");
            $fileName = $this->uploadFile("cvOdix");
            $cvOdix->setUrl($fileName);
            $candidat->addCv($cvOdix);
            $this->persistAndFlush($cvOdix);
        }
        

        //Ajout des technologies (une ou plusieurs)
        if(!empty($_POST['listeTechnologies']))
        {
            //Parcours et Ajout des technologies
            foreach ($_POST['listeTechnologies'] as $Technologie)
            {
                $technologieRepository = $this->getEntityManager()->getRepository(technologie::class);
                $technologie = $technologieRepository->findOneBy(array('id' => $Technologie));
                
                if (!$candidat->getListeTechnologies()->contains($technologie))
                {
                    $candidat->addTechnologie($technologie);
                }  
            }
            $this->persistAndFlush($candidat);
        }
        
        //Ajout des certifications (une ou plusieurs)
        if(!empty($_POST['listeCertifications']))
        {
            //Parcours et Ajout des certifications
            foreach ($_POST['listeCertifications'] as $Certification)
            {
                $certificationRepository = $this->getEntityManager()->getRepository(certification::class);
                $certification = $certificationRepository->findOneBy(array('id' => $Certification));
                
                if (!$candidat->getListeCErtifications()->contains($certification))
                {
                    $candidat->addCertification($certification);
                }  
                
            }
            $this->persistAndFlush($candidat);
        }
        
        $this->persistAndFlush($candidat);
        
    }
    
    public function deleteCandidat($idCandidat)
    {
        $candidat = $this->findOneBy(array('id' => $idCandidat));
        
        //Suppression de la Photo liée au candidat
        $photo = $candidat->getPhoto();
        if(!empty($photo))
        {
           unlink($photo);
        }
        
        //Suppression des CVs liés au candidat
        $listeCV = $candidat->getListeCvs();
        if(!empty($listeCV))
        {
            foreach ($listeCV as $cv)
            {
                unlink($cv->getUrl());
                
            }
        }
        
        $this->removeAndFlush($candidat);
    }
    
    public function removeTechnologieForCandidat($idCandidat,$idTechnologie)
    {
        $candidat = $this->findOneBy(array('id' => $idCandidat));
        
        $technologieRepository = $this->getEntityManager()->getRepository(technologie::class);
        $technologie = $technologieRepository->findOneBy(array('id' => $idTechnologie));
        
        $candidat->removeTechnologie($technologie);
        
        $this->persistAndFlush($candidat);

    }
    
    public function removeCertificationForCandidat($idCandidat,$idCertification)
    {
        $candidat = $this->findOneBy(array('id' => $idCandidat));
        
        $certificationRepository = $this->getEntityManager()->getRepository(certification::class);
        $certification = $certificationRepository->findOneBy(array('id' => $idCertification));
        
        $candidat->removeCertification($certification);
        
        $this->persistAndFlush($candidat);
        
    }

    public function archiveCandidat($idCandidat)
    {
        $candidat = $this->findOneBy(array('id' => $idCandidat));
        
        $candidat->setEtat("Archive");
        
        $this->persistAndFlush($candidat);
    }
    
    public function activeCandidat($idCandidat)
    {
        $candidat = $this->findOneBy(array('id' => $idCandidat));
        
        $candidat->setEtat("Active");
        
        $this->persistAndFlush($candidat);
    }
    
    public function showArchivedCandidats()
    {
        $candidats = $this->findBy(array('etat' => 'Archive'), array('prenom' => 'ASC'));
        
        $listeFinaleCandidats = array();
        
        foreach ($candidats as $candidat)
        {
            $photo = "bootstrap/img/profile.jpg";
            
            if(!empty($candidat->getPhoto()))
            {
                $photo = $candidat->getPhoto();
            }
            
            $anneeDemarrageCarriere = "N/A";
            
            if(!empty($candidat->getAnneeDemarrageCarriere()))
            {
                $anneeDemarrageCarriere = $candidat->getAnneeDemarrageCarriere();
            }
            
            $entreprise = "";
            
            if(!empty($candidat->getEntreprise()))
            {
                $entreprise = $candidat->getEntreprise()->getNom();
            }
            
            $listeCandidats = Array(
                'id' => $candidat->getId(),
                'prenom' => $candidat->getPrenom(),
                'nom' => $candidat->getNom(),
                'specialite' => $candidat->getSpecialite(),
                'telephone' => $candidat->getTelephone(),
                'anneeDemarrageCarriere' => $anneeDemarrageCarriere,
                'photo' => $photo,
                'visa' => $candidat->getVisa(),
                'etat' => $candidat->getEtat(),
                'entreprise' => $entreprise,
                'listeTechnologies' => $candidat->getListeTechnologies()
                );
            
            $listeFinaleCandidats[] = $listeCandidats;
        }
        return $listeFinaleCandidats;
        
    }
    
    public function uploadFile($fileName)
    {
        try
        {
            
            $filename = $_FILES[$fileName]["name"];
            $file_basename = substr($filename, 0, strripos($filename, '.')); // get file extention
            $file_ext = substr($filename, strripos($filename, '.')); // get file name
            $filesize = $_FILES[$fileName]["size"];
            $allowed_file_types = array('.doc','.docx','.jpg','.jpeg','.gif','.png','.pdf','.bmp');
            
            if (in_array($file_ext,$allowed_file_types) && ($filesize < 8388608 ))
            {
                // Rename file
                $newfilename = md5(uniqid()).$file_ext;
                if (file_exists("uploads/candidats/" . $newfilename))
                {
                    // file already exists error
                    echo "You have already uploaded this file.";
                }
                else
                {
                    move_uploaded_file($_FILES[$fileName]["tmp_name"], "uploads/candidats/".$newfilename);
                    echo "File uploaded successfully.";
                }
            }
            elseif (empty($file_basename))
            {
                // file selection error
                echo "Please select a file to upload.";
            }
            elseif ($filesize > 8388608 )
            {
                // file size error
                echo "The file you are trying to upload is too large.";
            }
            else
            {
                // file type error
                echo "Only these file typs are allowed for upload: " . implode(', ',$allowed_file_types);
                unlink($_FILES[$fileName]["tmp_name"]);
            }
            //retourne le nouveau nom du fichier dans le dossier /uploads
            return "uploads/candidats/".$newfilename;
            
        }
        catch(\Doctrine\DBAL\DBALException $e){}
    }

    
}
