<?php

namespace AppBundle\Repository;

use AppBundle\Entity\certification;

/**
 * certificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class certificationRepository extends \Doctrine\ORM\EntityRepository
{
    protected function persistAndFlush($entity)
    {
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();
        
    }
    
    protected function removeAndFlush($entity)
    {
        $this->getEntityManager()->remove($entity);
        $this->getEntityManager()->flush();
        
    }
    
    public function findAll()
    {
        return $this->findBy(array(), array('nom' => 'ASC'));
    }
    
    public function showAllCertifications()
    {
        $certifications = $this->findAll();
        
        $listeFinaleCertifications = array();
        
        foreach ($certifications as $certification)
        {
            $listeCertifications = Array(
                'id' => $certification->getId(),
                'nom' => $certification->getNom()
                );
            
            $listeFinaleCertifications[] = $listeCertifications;
        }
        return $listeFinaleCertifications;
        
    }
    
    public function deleteCertification($id)
    {
        
        $certification = $this->findOneBy(array('id' => $id));
        
        $this->removeAndFlush($certification);
        
    }
    
    public function addCertification($request)
    {
        
        $certification = new certification();
        
        try
        {
            if(!empty($request->get('nom')))
            {
                $certification->setNom($request->get('nom'));
            }
            
            $this->persistAndFlush($certification);
        }
        catch(\Doctrine\DBAL\DBALException $e){}
        
    }
    
    public function updateCertification($request)
    {
        
        $certification = $this->findOneBy(array('id' => $request->get('id')));
        
        try
        {
            if(!empty($request->get('nom')))
            {
                $certification->setNom($request->get('nom'));
            }
            
            $this->persistAndFlush($certification);
        }
        catch(\Doctrine\DBAL\DBALException $e){}
        
    }
}
