<?php

namespace AppBundle\Repository;

/**
 * cv_sauvegardeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cv_sauvegardeRepository extends \Doctrine\ORM\EntityRepository
{
}
