<?php

namespace AppBundle\Repository;

/**
 * diplomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class diplomeRepository extends \Doctrine\ORM\EntityRepository
{
    public function showAllDiplomes()
    {
        $diplomes = $this->findAll();
        
        $listeFinaleDiplomes = array();
        
        foreach ($diplomes as $diplome)
        {
            $listeDiplomes = Array(
                'id' => $diplome->getId(),
                'nom' => $diplome->getNom()
                );
            
            $listeFinaleDiplomes[] = $listeDiplomes;
        }
        return $listeFinaleDiplomes;
        
    }
}
