<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ecole;

/**
 * ecoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ecoleRepository extends \Doctrine\ORM\EntityRepository
{
    protected function persistAndFlush($entity)
    {
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();
        
    }
    
    protected function removeAndFlush($entity)
    {
        $this->getEntityManager()->remove($entity);
        $this->getEntityManager()->flush();
        
    }
    
    public function findAll()
    {
        return $this->findBy(array(), array('nom' => 'ASC'));
    }
    
    public function showAllEcoles()
    {
        $ecoles = $this->findAll();
        
        $listeFinaleEcoles = array();
        
        foreach ($ecoles as $ecole)
        {
            $listeEcoles = Array(
                'id' => $ecole->getId(),
                'nom' => $ecole->getNom()
                );
            
            $listeFinaleEcoles[] = $listeEcoles;
        }
        return $listeFinaleEcoles;
        
    }
    
    public function deleteEcole($id)
    {
        
        $ecole = $this->findOneBy(array('id' => $id));
        
        $this->removeAndFlush($ecole);
        
    }
    
    public function addEcole($request)
    {
        
        $ecole = new ecole();
        
        try
        {
            if(!empty($request->get('nom')))
            {
                $ecole->setNom($request->get('nom'));
            }
            
            $this->persistAndFlush($ecole);
        }
        catch(\Doctrine\DBAL\DBALException $e){}
        
    }
    
    public function updateEcole($request)
    {
        
        $ecole = $this->findOneBy(array('id' => $request->get('id')));
        
        try
        {
            if(!empty($request->get('nom')))
            {
                $ecole->setNom($request->get('nom'));
            }
            
            $this->persistAndFlush($ecole);
        }
        catch(\Doctrine\DBAL\DBALException $e){}
        
    }
}
