<?php

namespace AppBundle\Repository;

use AppBundle\Entity\entreprise;
use AppBundle\Entity\technologie;

/**
 * entrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entrepriseRepository extends \Doctrine\ORM\EntityRepository
{
    
    protected function persistAndFlush($entity)
    {
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();
        
    }
    
    protected function removeAndFlush($entity)
    {
        $this->getEntityManager()->remove($entity);
        $this->getEntityManager()->flush();
        
    }
    
    public function findAll()
    {
        return $this->findBy(array(), array('nom' => 'ASC'));
    }
    
    public function showAllEntreprises()
    {
        $entreprises = $this->findAll();
        
        $listeFinaleEntreprises = array();
        
        foreach ($entreprises as $entreprise)
        {
            $listeEntreprises = Array(
                'id' => $entreprise->getId(),
                'nom' => $entreprise->getNom(),
                'adresse' => $entreprise->getAdresse(),
                'siteWeb' => $entreprise->getSiteWeb(),
                'listeTechnologies' => $entreprise->getListeTechnologies()
                );
            
            $listeFinaleEntreprises[] = $listeEntreprises;
        }
        return $listeFinaleEntreprises;
        
    }
    
    public function showOneEntreprise($idEntreprise)
    {
        
        $entreprise = $this->findOneBy(array('id' => $idEntreprise));

        $listeEntreprise = Array(
                'id' => $entreprise->getId(),
                'nom' => $entreprise->getNom(),
                'adresse' => $entreprise->getAdresse(),
                'siteWeb' => $entreprise->getSiteWeb(),
                'listeTechnologies' => $entreprise->getListeTechnologies()
                );

        return $listeEntreprise;
        
    }
 
    public function deleteEntreprise($id)
    {
        
        $entreprise = $this->findOneBy(array('id' => $id));
        
        $this->removeAndFlush($entreprise);
        
    }
    
    public function addEntreprise($request)
    {
        
        $entreprise = new entreprise();
        
        try
        {
            if(!empty($request->get('nom')))
            {
                $entreprise->setNom($request->get('nom'));
            }
            
            if(!empty($request->get('adresse')))
            {
                $entreprise->setAdresse($request->get('adresse'));
            }
            
            if(!empty($request->get('siteWeb')))
            {
                $entreprise->setSiteWeb($request->get('siteWeb'));
            }
            
            //Ajout des technologies (une ou plusieurs)
            if(!empty($_POST['listeTechnologies']))
            {
                //Parcours et Ajout des technologies
                foreach ($_POST['listeTechnologies'] as $Technologie)
                {
                    $technologieRepository = $this->getEntityManager()->getRepository(technologie::class);
                    $technologie = $technologieRepository->findOneBy(array('id' => $Technologie));
                    
                    if(empty($technologie))
                    {
                        $technologie = new technologie();
                        $technologie->setNom($technologie);
                        $this->persistAndFlush($technologie);
                    }
                    $entreprise->addTechnologie($technologie);
                }
                $this->persistAndFlush($entreprise);
            }
            
            $this->persistAndFlush($entreprise);
        }
        catch(\Doctrine\DBAL\DBALException $e){}
        
    }
    
    public function updateEntreprise($request)
    {
        
        $entreprise = $this->findOneBy(array('id' => $request->get('id')));
        
        try
        {
            if(!empty($request->get('nom')))
            {
                $entreprise->setNom($request->get('nom'));
            }
            
            if(!empty($request->get('adresse')))
            {
                $entreprise->setAdresse($request->get('adresse'));
            }
            
            if(!empty($request->get('siteWeb')))
            {
                $entreprise->setSiteWeb($request->get('siteWeb'));
            }
            
            //Ajout des technologies (une ou plusieurs)
            if(!empty($_POST['listeTechnologies']))
            {
                //Parcours et Ajout des technologies
                foreach ($_POST['listeTechnologies'] as $Technologie)
                {
                    $technologieRepository = $this->getEntityManager()->getRepository(technologie::class);
                    $technologie = $technologieRepository->findOneBy(array('id' => $Technologie));
                    
                    if (!$entreprise->getListeTechnologies()->contains($technologie))
                    {
                        $entreprise->addTechnologie($technologie);
                    }
                }
                $this->persistAndFlush($entreprise);
            }
            
            $this->persistAndFlush($entreprise);
        }
        catch(\Doctrine\DBAL\DBALException $e){}
        
    }
    
    public function removeTechnologieForEntreprise($idEntreprise,$idTechnologie)
    {
        
        $entreprise = $this->findOneBy(array('id' => $idEntreprise));
        
        $technologieRepository = $this->getEntityManager()->getRepository(technologie::class);
        $technologie = $technologieRepository->findOneBy(array('id' => $idTechnologie));
        
        $entreprise->removeTechnologie($technologie);
        
        $this->persistAndFlush($entreprise);
        
    }
}
