<?php

namespace AppBundle\Repository;

use AppBundle\Entity\opportunite;
use \Datetime;
use AppBundle\Entity\candidat;
use AppBundle\Entity\utilisateur;
use AppBundle\Entity\technologie;
/**
 * opportuniteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class opportuniteRepository extends \Doctrine\ORM\EntityRepository
{
    protected function persistAndFlush($entity)
    {
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();
        
    }
    
    protected function removeAndFlush($entity)
    {
        $this->getEntityManager()->remove($entity);
        $this->getEntityManager()->flush();
        
    }
    
    public function findAll()
    {
        return $this->findBy(array('etat' => 'Active'), array('dateDemarrageSouhaitee' => 'ASC'));
    }
    
    public function showAllOpportunites()
    {
        
        $opportunites = $this->findAll();

        $listeFinaleOpportunites = array();
        
        foreach ($opportunites as $opportunite)
        {
            $dateAjout = "N/A";
            $dateDemarrageSouhaitee = "N/A";
            $tjm = "N/A";
            $photo = "bootstrap/img/profile.jpg";
            
            
            if(!empty($opportunite->getDateAjout()))
            {
                $dateAjout = $opportunite->getDateAjout()->format('d-m-Y');
            }
            
            if(!empty($opportunite->getDateDemarrageSouhaitee()))
            {
                $dateDemarrageSouhaitee = $opportunite->getDateDemarrageSouhaitee()->format('d-m-Y');
            }
            
            if(!empty($opportunite->getTjm()))
            {
                $tjm = $opportunite->getTjm();
            }
            
            if(!empty($opportunite->getUtilisateur()->getPhoto()))
            {
                $photo = $opportunite->getUtilisateur()->getPhoto();
            }
            
            
            $listeOpportunites = Array(
                'id' => $opportunite->getId(),
                'titre' => $opportunite->getTitre(),
                'etat' => $opportunite->getEtat(),
                'descriptionDetaillee' => $opportunite->getDescriptionDetaillee(),
                'dateAjout' => $dateAjout,
                'tjm' => $tjm,
                'dateDemarrageSouhaitee' => $dateDemarrageSouhaitee,
                
                
                'utilisateur' => $opportunite->getUtilisateur()->getPrenom().' '.$opportunite->getUtilisateur()->getNom(),
                'idUtilisateur' => $opportunite->getUtilisateur()->getId(),
                'photo' => $photo,
                
                'listeCandidats' => $opportunite->getListeCandidats(),
                'listeTechnologies' => $opportunite->getListeTechnologies()
                
                );
            
            $listeFinaleOpportunites[] = $listeOpportunites;
        }
        return $listeFinaleOpportunites;
        
    }
    
    public function showOneOpportunite($idOpportunite)
    {
        $opportunite = $this->findOneBy(array('id' => $idOpportunite));
        
        $dateAjout = "N/A";
        $dateDemarrageSouhaitee = "N/A";
        $tjm = "N/A";
        $photo = "bootstrap/img/profile.jpg";
            
            if(!empty($opportunite->getDateAjout()))
            {
                $dateAjout = $opportunite->getDateAjout()->format('d-m-Y');
            }
            
            if(!empty($opportunite->getDateDemarrageSouhaitee()))
            {
                $dateDemarrageSouhaitee = $opportunite->getDateDemarrageSouhaitee()->format('d-m-Y');
            }
            
            if(!empty($opportunite->getTjm()))
            {
                $tjm = $opportunite->getTjm();
            }
            
            if(!empty($opportunite->getUtilisateur()->getPhoto()))
            {
                $photo = $opportunite->getUtilisateur()->getPhoto();
            }
            
            
            
        $listeOpportunites = Array(
                'id' => $opportunite->getId(),
                'titre' => $opportunite->getTitre(),
                'etat' => $opportunite->getEtat(),
                'descriptionDetaillee' => $opportunite->getDescriptionDetaillee(),
            
                'dateAjout' => $dateAjout,
                'tjm' => $tjm,
                'dateDemarrageSouhaitee' => $dateDemarrageSouhaitee,
                
                'utilisateur' => $opportunite->getUtilisateur()->getPrenom().' '.$opportunite->getUtilisateur()->getNom(),
                'idUtilisateur' => $opportunite->getUtilisateur()->getId(),
                'photo' => $photo,
                
                'listeCandidats' => $opportunite->getListeCandidats(),
                'listeTechnologies' => $opportunite->getListeTechnologies()
                
                );

        
        return $listeOpportunites;
        
    }
    
    public function deleteOpportunite($idOpportunite)
    {
        $opportunite = $this->findOneBy(array('id' => $idOpportunite));
        
        $this->removeAndFlush($opportunite);
    }
    
    public function addOpportunite($request)
    {
        $opportunite = new opportunite();
        
        $opportunite->setEtat("Active");
        
        if(!empty($request->get('titre')))
        {
            $opportunite->setTitre($request->get('titre'));
        }
        
        if(!empty($request->get('descriptionDetaillee')))
        {
            $opportunite->setDescriptionDetaillee($request->get('descriptionDetaillee'));
        }

        if(!empty($request->get('dateDemarrageSouhaitee')))
        {
            $opportunite->setDateDemarrageSouhaitee(new DateTime($request->get('dateDemarrageSouhaitee')));
        }
        
        $opportunite->setDateAjout(new DateTime());
        
        if(!empty($request->get('tjm')))
        {
            $opportunite->setTjm($request->get('tjm'));
        }
        
        //Ajout du Partenaire responsable de l'opportunité
        if(!empty($request->get('listePartenaires')))
        {
            $partenaireRepository = $this->getEntityManager()->getRepository(utilisateur::class);
            $partenaire = $partenaireRepository->findOneBy(array('id' => $request->get('listePartenaires')));
            $opportunite->setUtilisateur($partenaire);
        }
        
        
        //Ajout des candidats potentiels à l'opportunité
        if(!empty($_POST['listeCandidats']))
        {
            //Parcours et Ajout des candidats
            foreach ($_POST['listeCandidats'] as $idCandidat)
            {
                $candidatRepository = $this->getEntityManager()->getRepository(candidat::class);
                $candidat = $candidatRepository->findOneBy(array('id' => $idCandidat));
                
                $opportunite->addCandidat($candidat);
            }
        }
        
        //Ajout des technologies (une ou plusieurs)
        if(!empty($_POST['listeTechnologies']))
        {
            //Parcours et Ajout des technologies
            foreach ($_POST['listeTechnologies'] as $Technologie)
            {
                $technologieRepository = $this->getEntityManager()->getRepository(technologie::class);
                $technologie = $technologieRepository->findOneBy(array('id' => $Technologie));
                
                if(empty($technologie))
                {
                    $technologie = new technologie();
                    $technologie->setNom($technologie);
                    $this->persistAndFlush($technologie);
                }
                $opportunite->addTechnologie($technologie);
            }
            $this->persistAndFlush($opportunite);
        }
        
        $this->persistAndFlush($opportunite);
    }
    
    public function updateOpportunite($request)
    {
        
        $opportunite = $this->findOneBy(array('id' => $request->get('id')));
        
        if(!empty($request->get('titre')))
        {
            $opportunite->setTitre($request->get('titre'));
        }
        
        if(!empty($request->get('descriptionDetaillee')))
        {
            $opportunite->setDescriptionDetaillee($request->get('descriptionDetaillee'));
        }
        
        if(!empty($request->get('dateDemarrageSouhaitee')))
        {
            $opportunite->setDateDemarrageSouhaitee(new DateTime($request->get('dateDemarrageSouhaitee')));
        }
        
        //$opportunite->setDateAjout(new DateTime());
        
        if(!empty($request->get('tjm')))
        {
            $opportunite->setTjm($request->get('tjm'));
        }
        
        //Ajout du Partenaire responsable de l'opportunité
        if(!empty($request->get('listePartenaires')))
        {
            $partenaireRepository = $this->getEntityManager()->getRepository(utilisateur::class);
            $partenaire = $partenaireRepository->findOneBy(array('id' => $request->get('listePartenaires')));
            $opportunite->setUtilisateur($partenaire);
        }
        
        
        //Ajout des candidats potentiels à l'opportunité
        if(!empty($_POST['listeCandidats']))
        {
            //Parcours et Ajout des candidats
            foreach ($_POST['listeCandidats'] as $idCandidat)
            {
                $candidatRepository = $this->getEntityManager()->getRepository(candidat::class);
                $candidat = $candidatRepository->findOneBy(array('id' => $idCandidat));
                
                if (!$opportunite->getListeCandidats()->contains($candidat))
                {
                    $opportunite->addCandidat($candidat);
                }  
            }
            
        }
        
        //Ajout des technologies (une ou plusieurs)
        if(!empty($_POST['listeTechnologies']))
        {
            //Parcours et Ajout des technologies
            foreach ($_POST['listeTechnologies'] as $Technologie)
            {
                $technologieRepository = $this->getEntityManager()->getRepository(technologie::class);
                $technologie = $technologieRepository->findOneBy(array('id' => $Technologie));
                
                if (!$opportunite->getListeTechnologies()->contains($technologie))
                {
                    $opportunite->addTechnologie($technologie);
                }
                
            }
            $this->persistAndFlush($opportunite);
        }
        
        $this->persistAndFlush($opportunite);
    }
    
    public function removeCandidatForOpportunite($idOpportunite, $idCandidat)
    {
        
        $opportunite = $this->findOneBy(array('id' => $idOpportunite));
        
        $candidatRepository = $this->getEntityManager()->getRepository(candidat::class);
        $candidat = $candidatRepository->findOneBy(array('id' => $idCandidat));
        
        $opportunite->removeCandidat($candidat);
        
        $this->persistAndFlush($opportunite);
        
    }
    
    public function removeTechnologieForOpportunite($idOpportunite,$idTechnologie)
    {
        $opportunite = $this->findOneBy(array('id' => $idOpportunite));
        
        $technologieRepository = $this->getEntityManager()->getRepository(technologie::class);
        $technologie = $technologieRepository->findOneBy(array('id' => $idTechnologie));
        
        $opportunite->removeTechnologie($technologie);
        
        $this->persistAndFlush($opportunite);
        
    }
    
    public function archiveOpportunite($idOpportunite)
    {
        $opportunite = $this->findOneBy(array('id' => $idOpportunite));
        
        $opportunite->setEtat("Archive");
        
        $this->persistAndFlush($opportunite);
    }
    
    public function activeOpportunite($idOpportunite)
    {
        $opportunite = $this->findOneBy(array('id' => $idOpportunite));
        
        $opportunite->setEtat("Active");
        
        $this->persistAndFlush($opportunite);
    }
    
    public function showArchivedOpportunites()
    {
        $opportunites = $this->findBy(array('etat' => 'Archive'), array('dateAjout' => 'DESC'));
        
        $listeFinaleOpportunites = array();
        
        foreach ($opportunites as $opportunite)
        {
            $dateAjout = "N/A";
            $dateDemarrageSouhaitee = "N/A";
            $tjm = "N/A";
            $photo = "bootstrap/img/profile.jpg";
            
            
            if(!empty($opportunite->getDateAjout()))
            {
                $dateAjout = $opportunite->getDateAjout()->format('d-m-Y');
            }
            
            if(!empty($opportunite->getDateDemarrageSouhaitee()))
            {
                $dateDemarrageSouhaitee = $opportunite->getDateDemarrageSouhaitee()->format('d-m-Y');
            }
            
            if(!empty($opportunite->getTjm()))
            {
                $tjm = $opportunite->getTjm();
            }
            
            if(!empty($opportunite->getUtilisateur()->getPhoto()))
            {
                $photo = $opportunite->getUtilisateur()->getPhoto();
            }
            
            
            $listeOpportunites = Array(
                'id' => $opportunite->getId(),
                'titre' => $opportunite->getTitre(),
                'etat' => $opportunite->getEtat(),
                'descriptionDetaillee' => $opportunite->getDescriptionDetaillee(),
                'dateAjout' => $dateAjout,
                'tjm' => $tjm,
                'dateDemarrageSouhaitee' => $dateDemarrageSouhaitee,
                
                
                'utilisateur' => $opportunite->getUtilisateur()->getPrenom().' '.$opportunite->getUtilisateur()->getNom(),
                'photo' => $photo,
                
                'listeCandidats' => $opportunite->getListeCandidats()
                
                );
            
            $listeFinaleOpportunites[] = $listeOpportunites;
        }
        return $listeFinaleOpportunites;
    }
    
   
}
