<?php

namespace AppBundle\Repository;

use AppBundle\Entity\rappel;
use \Datetime;
use AppBundle\Entity\utilisateur;

/**
 * rappelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rappelRepository extends \Doctrine\ORM\EntityRepository
{
    
    protected function persistAndFlush($entity)
    {
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();
        
    }
    
    protected function removeAndFlush($entity)
    {
        $this->getEntityManager()->remove($entity);
        $this->getEntityManager()->flush();
        
    }
    
    public function findAll()
    {
        return $this->findBy(array(), array('datetime' => 'DESC'));
    }
    
    public function showAllRappels()
    {
        $rappels = $this->findAll();

        $listeFinaleRappels = array();
        
        foreach ($rappels as $rappel)
        {
            
            $datetime = "N / A";
            if(!empty($rappel->getDatetime()))
            {
                $datetime = $rappel->getDatetime()->format('Y-m-d H:i');
            }
            
            $listeRappels = Array(
                'id' => $rappel->getId(),
                'description' => $rappel->getDescription(),
                'datetime' => $datetime
                );
            
            $listeFinaleRappels[] = $listeRappels;
        }
        return $listeFinaleRappels;
        
    }
    
    public function addRappel($request)
    {
        
        $rappel = new rappel();
        
        /*if(!empty($utilisateur))
        {
            $rappel->setUtilisateur($utilisateur);
        }*/
        
        $utilisateurRepository = $this->getEntityManager()->getRepository(utilisateur::class);
        $utilisateur = $utilisateurRepository->findOneBy(array('id' => '1'));
        
        $rappel->setUtilisateur($utilisateur);

        if(!empty($request->get('description')))
        {
            $rappel->setDescription($request->get('description'));
        }
        
        if(!empty($request->get('datetime')))
        {
            $rappel->setDatetime((new DateTime($request->get('datetime'))));
        }
            
        $this->persistAndFlush($rappel);
        
    }
    
    public function updateRappel($request)
    {
        
        $rappel = $this->findOneBy(array('id' => $request->get('id')));
        
        if(!empty($request->get('description')))
        {
            $rappel->setDescription($request->get('description'));
        }
        
        if(!empty($request->get('datetime')))
        {
            $rappel->setDatetime((new DateTime($request->get('datetime'))));
        }
        
        $this->persistAndFlush($rappel);
        
    }
    
    public function deleteRappel($id)
    {
        
        $rappel = $this->findOneBy(array('id' => $id));
        
        $this->removeAndFlush($rappel);
        
    }
}
