<?php

namespace AppBundle\Repository;

/**
 * recherche_sauvegardeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class recherche_sauvegardeRepository extends \Doctrine\ORM\EntityRepository
{
}
