<?php

namespace AppBundle\Repository;

use AppBundle\Entity\technologie;

/**
 * technologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class technologieRepository extends \Doctrine\ORM\EntityRepository
{
    protected function persistAndFlush($entity)
    {
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();
        
    }
    
    protected function removeAndFlush($entity)
    {
        $this->getEntityManager()->remove($entity);
        $this->getEntityManager()->flush();
        
    }
    
    public function findAll()
    {
        return $this->findBy(array(), array('nom' => 'ASC'));
    }
    
    public function showAllTechnologies()
    {
        $technologies = $this->findAll();
        
        $listeFinaleTechnologies = array();
        
        foreach ($technologies as $technologie)
        {
            $listeTechnologies = Array(
                'id' => $technologie->getId(),
                'nom' => $technologie->getNom()
                );
            
            $listeFinaleTechnologies[] = $listeTechnologies;
        }
        return $listeFinaleTechnologies;
        
    }

    public function deleteTechnologie($id)
    {
        
        $technologie = $this->findOneBy(array('id' => $id));
        
        $this->removeAndFlush($technologie);
        
    }
    
    public function addTechnologie($request)
    { 
        
        $technologie = new technologie();

        try
        {
            if(!empty($request->get('nom')))
            {
                $technologie->setNom($request->get('nom'));
            }
            
            $this->persistAndFlush($technologie);
        }
        catch(\Doctrine\DBAL\DBALException $e){} 
        
    }
    
    public function updateTechnologie($request)
    {
        
        $technologie = $this->findOneBy(array('id' => $request->get('id')));

        try
        {
            if(!empty($request->get('nom')))
            {
                $technologie->setNom($request->get('nom'));
            }
            
            $this->persistAndFlush($technologie);
        }
        catch(\Doctrine\DBAL\DBALException $e){} 
        
    }

}
