<?php

namespace AppBundle\Repository;

use AppBundle\Entity\utilisateur;
use AppBundle\Entity\entreprise;
use AppBundle\Entity\technologie;
use Symfony\Component\HttpFoundation\Request;

/**
 * utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class utilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    
    protected function persistAndFlush($entity)
    {
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();
        
    }
    
    protected function removeAndFlush($entity)
    {
        $this->getEntityManager()->remove($entity);
        $this->getEntityManager()->flush();
        
    }
    
    public function findAll()
    {
        return $this->findBy(array(), array('prenom' => 'ASC'));
    }
    
    public function showAllPartenaires()
    {
        $partenaires = $this->findAll();
        
        $listeFinalePartenaires = array();
        
        foreach ($partenaires as $partenaire)
        {
            $photo = "bootstrap/img/profile.jpg";
            
            if(!empty($partenaire->getPhoto()))
            {
                $photo = $partenaire->getPhoto();
            }
            
            $entreprise = "N / A";
            $idEntreprise = "";
            
            if(!empty($partenaire->getEntreprise()))
            {
                $entreprise = $partenaire->getEntreprise()->getNom();
                $idEntreprise = $partenaire->getEntreprise()->getId();
            }

            $listePartenaires = Array(
                'id' => $partenaire->getId(),
                'prenom' => $partenaire->getPrenom(),
                'nom' => $partenaire->getNom(),
                'login' => $partenaire->getLogin(),
                'password' => $partenaire->getPassword(),
                'photo' => $photo,
                'type' => $partenaire->getType(),
                'telephone' => $partenaire->getTelephone(),
                'email' => $partenaire->getEmail(),
                'poste' => $partenaire->getPoste(),
                'descriptionDetaillee' => $partenaire->getDescriptionDetaillee(),
                'entreprise' => $entreprise,
                'listeTechnologies' => $idEntreprise
                
                );
            
            $listeFinalePartenaires[] = $listePartenaires;
        }
        return $listeFinalePartenaires;
        
    }
    
    public function showAllPartenairesLight()
    {
        $partenaires = $this->findAll();
        
        $listeFinalePartenaires = array();
        
        foreach ($partenaires as $partenaire)
        {
            
            $listePartenaires = Array(
                'id' => $partenaire->getId(),
                'prenom' => $partenaire->getPrenom(),
                'nom' => $partenaire->getNom()
                
                );
            
            $listeFinalePartenaires[] = $listePartenaires;
        }
        return $listeFinalePartenaires;
        
    }
    
    public function showOnePartenaire($idPartenaire)
    {
        $partenaire = $this->findOneBy(array('id' => $idPartenaire));
        
        $photo = "bootstrap/img/profile.jpg";
            
        if(!empty($partenaire->getPhoto()))
        {
           $photo = $partenaire->getPhoto();
        }
        
        $entreprise = "N / A";
        $idEntreprise = "";
        
        if(!empty($partenaire->getEntreprise()))
        {
            $entreprise = $partenaire->getEntreprise()->getNom();
            $idEntreprise = $partenaire->getEntreprise()->getId();
        }
            
        $detailsPartenaire = Array(
                'id' => $partenaire->getId(),
                'prenom' => $partenaire->getPrenom(),
                'nom' => $partenaire->getNom(),
                'login' => $partenaire->getLogin(),
                'password' => $partenaire->getPassword(),
                'photo' => $photo,
                'type' => $partenaire->getType(),
                'telephone' => $partenaire->getTelephone(),
                'email' => $partenaire->getEmail(),
                'poste' => $partenaire->getPoste(),
                'descriptionDetaillee' => $partenaire->getDescriptionDetaillee(),
                'entreprise' => $entreprise,
                'idEntreprise' => $idEntreprise,
                'listeTechnologies' => $partenaire->getListeTechnologies()
                
         );
        
        return $detailsPartenaire;
        
    }
    
    public function deletePartenaire($idPartenaire)
    {
        $partenaire = $this->findOneBy(array('id' => $idPartenaire));
        
        //Suppression de la Photo liée au partenaire
        $photo = $partenaire->getPhoto();
        if(!empty($photo))
        {
            unlink($photo);
        }
        
        $this->removeAndFlush($partenaire);
    }
    
    public function addPartenaire($request)
    {
        
        $partenaire = new utilisateur();
        
        if(!empty($request->get('prenom')))
        {
            $partenaire->setPrenom($request->get('prenom'));
        }
        
        if(!empty($request->get('nom')))
        {
            $partenaire->setNom($request->get('nom'));
        }
        
        if(!empty($request->get('login')))
        {
            $partenaire->setLogin($request->get('login'));
        }
        
        if(!empty($request->get('password')))
        {
            $partenaire->setPassword($request->get('password'));
        }
        
        //Ajout de la Photo
        if(!empty($_FILES["photoTelechargement"]["name"]))
        {
            $partenaire->setPhoto($this->uploadFile("photoTelechargement"));
        }
        
        if(!empty($request->get('type')))
        {
            $partenaire->setType($request->get('type'));
        }
        
        if(!empty($request->get('telephone')))
        {
            $partenaire->setTelephone($request->get('telephone'));
        }
        
        if(!empty($request->get('email')))
        {
            $partenaire->setEmail($request->get('email'));
        }
        
        if(!empty($request->get('poste')))
        {
            $partenaire->setPoste($request->get('poste'));
        }
           
        if(!empty($request->get('descriptionDetaillee')))
        {
            $partenaire->setDescriptionDetaillee($request->get('descriptionDetaillee'));
        }
        

        //Ajout de l'Entreprise
        if(!empty($request->get('listeEntreprises')))
        {
            $entrepriseRepository = $this->getEntityManager()->getRepository(entreprise::class);
            $entreprise = $entrepriseRepository->findOneBy(array('id' => $request->get('listeEntreprises')));
            $partenaire->setEntreprise($entreprise);
        }
        
        //Ajout des technologies (une ou plusieurs)
        if(!empty($_POST['listeTechnologies']))
        {
            //Parcours et Ajout des technologies
            foreach ($_POST['listeTechnologies'] as $Technologie)
            {
                $technologieRepository = $this->getEntityManager()->getRepository(technologie::class);
                $technologie = $technologieRepository->findOneBy(array('id' => $Technologie));
                
                if(empty($technologie))
                {
                    $technologie = new technologie();
                    $technologie->setNom($technologie);
                    $this->persistAndFlush($technologie);
                }
                $partenaire->addTechnologie($technologie);
            }
            $this->persistAndFlush($partenaire);
        }

        $this->persistAndFlush($partenaire);
    }

    public function updatePartenaire($request)
    {
        
        $partenaire = $this->findOneBy(array('id' => $request->get('id')));
        
        if(!empty($request->get('prenom')))
        {
            $partenaire->setPrenom($request->get('prenom'));
        }
        
        if(!empty($request->get('nom')))
        {
            $partenaire->setNom($request->get('nom'));
        }
        
        if(!empty($request->get('login')))
        {
            $partenaire->setLogin($request->get('login'));
        }
        
        if(!empty($request->get('password')))
        {
            $partenaire->setPassword($request->get('password'));
        }
        
        //Ajout de la Photo
        if(!empty($_FILES["photoTelechargement"]["name"]))
        {
            unlink($partenaire->getPhoto());
            
            $partenaire->setPhoto($this->uploadFile("photoTelechargement"));
        }
        
        if(!empty($request->get('type')))
        {
            $partenaire->setType($request->get('type'));
        }
        
        if(!empty($request->get('telephone')))
        {
            $partenaire->setTelephone($request->get('telephone'));
        }
        
        if(!empty($request->get('email')))
        {
            $partenaire->setEmail($request->get('email'));
        }
        
        if(!empty($request->get('poste')))
        {
            $partenaire->setPoste($request->get('poste'));
        }
        
        if(!empty($request->get('descriptionDetaillee')))
        {
            $partenaire->setDescriptionDetaillee($request->get('descriptionDetaillee'));
        }
        
        
        //Ajout de l'Entreprise
        if(!empty($request->get('listeEntreprises')))
        {
            $entrepriseRepository = $this->getEntityManager()->getRepository(entreprise::class);
            $entreprise = $entrepriseRepository->findOneBy(array('id' => $request->get('listeEntreprises')));
            $partenaire->setEntreprise($entreprise);
        }
        
        //Ajout des technologies (une ou plusieurs)
        if(!empty($_POST['listeTechnologies']))
        {
            //Parcours et Ajout des technologies
            foreach ($_POST['listeTechnologies'] as $Technologie)
            {
                $technologieRepository = $this->getEntityManager()->getRepository(technologie::class);
                $technologie = $technologieRepository->findOneBy(array('id' => $Technologie));
                
                if (!$partenaire->getListeTechnologies()->contains($technologie))
                {
                    $partenaire->addTechnologie($technologie);
                }  
                
            }
            //$this->persistAndFlush($partenaire);
        }
        try
        {
            $this->persistAndFlush($partenaire);
        }catch(\Doctrine\DBAL\DBALException $e){throw $e;}
 
    }
    
    public function uploadFile($fileName)
    {
        try
        {
            
            $filename = $_FILES[$fileName]["name"];
            $file_basename = substr($filename, 0, strripos($filename, '.')); // get file extention
            $file_ext = substr($filename, strripos($filename, '.')); // get file name
            $filesize = $_FILES[$fileName]["size"];
            $allowed_file_types = array('.doc','.docx','.jpg','.jpeg','.gif','.png','.pdf');
            
            if (in_array($file_ext,$allowed_file_types) && ($filesize < 8388608 ))
            {
                // Rename file
                $newfilename = md5(uniqid()).$file_ext;
                if (file_exists("uploads/partenaires/" . $newfilename))
                {
                    // file already exists error
                    echo "You have already uploaded this file.";
                }
                else
                {
                    move_uploaded_file($_FILES[$fileName]["tmp_name"], "uploads/partenaires/".$newfilename);
                    echo "File uploaded successfully.";
                }
            }
            elseif (empty($file_basename))
            {
                // file selection error
                echo "Please select a file to upload.";
            }
            elseif ($filesize > 8388608 )
            {
                // file size error
                echo "The file you are trying to upload is too large.";
            }
            else
            {
                // file type error
                echo "Only these file typs are allowed for upload: " . implode(', ',$allowed_file_types);
                unlink($_FILES[$fileName]["tmp_name"]);
            }
            //retourne le nouveau nom du fichier dans le dossier /uploads
            return "uploads/partenaires/".$newfilename;
            
        }
        catch(\Doctrine\DBAL\DBALException $e){}
    }

    public function loginUtilisateur($request)
    {

        $login = $request->get('login');
        $password = $request->get('password');
        
        $utilisateur = $this->findOneBy(array('login' => $login, 'password' => $password));
  
        return $utilisateur;
    }

    public function showAllContacts()
    {
        $contacts = $this->findAll();
        
        $listeFinaleContacts = array();
        
        foreach ($contacts as $contact)
        {
            $photo = "bootstrap/img/profile.jpg";
            
            if(!empty($contact->getPhoto()))
            {
                $photo = $contact->getPhoto();
            }
            
            $entreprise = "N / A";
            
            if(!empty($contact->getEntreprise()))
            {
                $entreprise = $contact->getEntreprise()->getNom();
            }
            
            $listeContacts = Array(
                'id' => $contact->getId(),
                'prenom' => $contact->getPrenom(),
                'nom' => $contact->getNom(),
                'photo' => $photo,
                'type' => $contact->getType(),
                'telephone' => $contact->getTelephone(),
                'email' => $contact->getEmail(),
                'poste' => $contact->getPoste(),
                'descriptionDetaillee' => $contact->getDescriptionDetaillee(),
                'entreprise' => $entreprise
                
                );
            
            $listeFinaleContacts[] = $listeContacts;
        }
        return $listeFinaleContacts;
        
    }
    
    public function addContact($request)
    {
        
        $contact = new utilisateur();
        
        if(!empty($request->get('prenom')))
        {
            $contact->setPrenom($request->get('prenom'));
        }
        
        if(!empty($request->get('nom')))
        {
            $contact->setNom($request->get('nom'));
        }

        //Ajout de la Photo
        if(!empty($_FILES["photoTelechargement"]["name"]))
        {
            $contact->setPhoto($this->uploadFile("photoTelechargement"));
        }
        
        if(!empty($request->get('type')))
        {
            $contact->setType($request->get('type'));
        }
        
        if(!empty($request->get('telephone')))
        {
            $contact->setTelephone($request->get('telephone'));
        }
        
        if(!empty($request->get('email')))
        {
            $contact->setEmail($request->get('email'));
        }
        
        if(!empty($request->get('poste')))
        {
            $contact->setPoste($request->get('poste'));
        }
        
        if(!empty($request->get('descriptionDetaillee')))
        {
            $contact->setDescriptionDetaillee($request->get('descriptionDetaillee'));
        }
        
        
        //Ajout de l'Entreprise
        if(!empty($request->get('listeEntreprises')))
        {
            $entrepriseRepository = $this->getEntityManager()->getRepository(entreprise::class);
            $entreprise = $entrepriseRepository->findOneBy(array('id' => $request->get('listeEntreprises')));
            
            $contact->setEntreprise($entreprise);
        }
        
        $this->persistAndFlush($contact);
    }

    public function showOneContact($idContact)
    {
        $contact = $this->findOneBy(array('id' => $idContact));
        
        $photo = "bootstrap/img/profile.jpg";
        
        if(!empty($contact->getPhoto()))
        {
            $photo = $contact->getPhoto();
        }
        
        $entreprise = "N / A";
        $idEntreprise = "";
        
        if(!empty($contact->getEntreprise()))
        {
            $entreprise = $contact->getEntreprise()->getNom();
            $idEntreprise = $contact->getEntreprise()->getId();
        }
        
        $detailsContact = Array(
            'id' => $contact->getId(),
            'prenom' => $contact->getPrenom(),
            'nom' => $contact->getNom(),
            'photo' => $photo,
            'type' => $contact->getType(),
            'telephone' => $contact->getTelephone(),
            'email' => $contact->getEmail(),
            'poste' => $contact->getPoste(),
            'descriptionDetaillee' => $contact->getDescriptionDetaillee(),
            'entreprise' => $entreprise,
            'idEntreprise' => $idEntreprise
            
            );
        
        return $detailsContact;
        
    }
    
    public function deleteContact($idContact)
    {
        $contact = $this->findOneBy(array('id' => $idContact));
        
        //Suppression de la Photo liée au contact
        $photo = $contact->getPhoto();
        if(!empty($photo))
        {
            unlink($photo);
        }
        
        $this->removeAndFlush($contact);
    }

    public function updateContact($request)
    {
        
        $contact = $this->findOneBy(array('id' => $request->get('id')));
        
        if(!empty($request->get('prenom')))
        {
            $contact->setPrenom($request->get('prenom'));
        }
        
        if(!empty($request->get('nom')))
        {
            $contact->setNom($request->get('nom'));
        }
        
        //Ajout de la Photo
        if(!empty($_FILES["photoTelechargement"]["name"]))
        {
            unlink($contact->getPhoto());
            
            $contact->setPhoto($this->uploadFile("photoTelechargement"));
        }
        
        if(!empty($request->get('type')))
        {
            $contact->setType($request->get('type'));
        }
        
        if(!empty($request->get('telephone')))
        {
            $contact->setTelephone($request->get('telephone'));
        }
        
        if(!empty($request->get('email')))
        {
            $contact->setEmail($request->get('email'));
        }
        
        if(!empty($request->get('poste')))
        {
            $contact->setPoste($request->get('poste'));
        }
        
        if(!empty($request->get('descriptionDetaillee')))
        {
            $contact->setDescriptionDetaillee($request->get('descriptionDetaillee'));
        }
        
        
        //Ajout de l'Entreprise
        if(!empty($request->get('listeEntreprises')))
        {
            $entrepriseRepository = $this->getEntityManager()->getRepository(entreprise::class);
            $entreprise = $entrepriseRepository->findOneBy(array('id' => $request->get('listeEntreprises')));
            $contact->setEntreprise($entreprise);
        }
        
        $this->persistAndFlush($contact);
    }
    
    public function removeTechnologieForPartenaire($idPartenaire,$idTechnologie)
    {
        $partenaire = $this->findOneBy(array('id' => $idPartenaire));
        
        $technologieRepository = $this->getEntityManager()->getRepository(technologie::class);
        $technologie = $technologieRepository->findOneBy(array('id' => $idTechnologie));
        
        $partenaire->removeTechnologie($technologie);
        
        $this->persistAndFlush($partenaire);
        
    }
}
